Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2023
Var

nome: caractere
idade, contador: inteiro

Inicio
Para contador de 1 ate 3 faca
 Escreva("Insira um nome: ")
 Leia(nome)

 Escreva("Insira uma idade: ")
 Leia(idade)

 Limpatela()
Fimpara

Fimalgoritmo