Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2023
Var

num, cont: inteiro

Inicio

num <- 4

Para cont de 1 ate 46 faca
 num <- num + 1
 Se (num mod 2 <> 0) entao
 Escreva(num)
 Fimse
Fimpara

Fimalgoritmo