Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2023
Var

ano: inteiro

Inicio
Escreva("Digite um ano (4 dígitos): ")
Leia(ano)

Se (ano % 4 = 0) entao
Escreva(ano, " é um ano bissexto.")
Senao
Escreva(ano, " não é um ano bissexto.")
Fimse

Fimalgoritmo