Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2023
Var

num: inteiro

Inicio
Escreva("Insira um numero: ")
Leia(num)

Se (num mod 2 = 0) entao
Escreva("O numero é par!")
Senao
Escreva("O numero é impar!")
Fimse


Fimalgoritmo