Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2023
Var

num: inteiro

Inicio
Escreva("Insira um número entre 10 e 45: ")
Leia(num)

Se (num >= 10) e (num <= 45) entao
Escreva("O número é válido")
Senao
Escreva("O número é inválido")
Fimse

Fimalgoritmo