Algoritmo "Volume de um Prisma"

Var
   L1, L2, L3, VPM: real

Inicio
   Escreva("Digite o comprimento da primeira aresta do prisma: ")
   Leia(L1)

   Escreva("Digite o comprimento da segunda aresta do prisma: ")
   Leia(L2)

   Escreva("Digite o comprimento da terceira aresta do prisma: ")
   Leia(L3)

   VPM <- L1 * L2 * L3

   Escreva("O volume do prisma é: ")
   Escreval(VPM)

Fimalgoritmo