Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2023
Var

nome: caractere
idade, contador: inteiro

Inicio
Repita
 contador <- contador + 1
 
 Escreva("Insira um nome: ")
 Leia(nome)

 Escreva("Insira uma idade: ")
 Leia(idade)
 
 Limpatela()
Ate (contador = 3)


Fimalgoritmo