Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Thyago Bohrer Borges 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2023
Var

num, soma, cont: inteiro

Inicio

Para cont de 1 ate 15 faca
 Escreva("Insira um numero: ")
 Leia(soma)
 num <- num + soma
Fimpara

Escreva ("A média entre todos os numeros é: ", num/15)

Fimalgoritmo