Algoritmo "Décima parte da subtração"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

num1, num2, subtracao: real

Inicio
Escreva ("Digite o primeiro numero: ")
Leia (num1)

Escreva ("Digite o segundo numero: ")
Leia (num2)

subtracao <- num1 - num2

Escreva ("Essa é a décima parte da subtração: ", subtracao/10)

Fimalgoritmo