Algoritmo "Multiplicação de 3 Números Inteiros"

Var
   num1, num2, num3, resultado: inteiro

Inicio
   Escreva("Digite o primeiro número inteiro: ")
   Leia(num1)

   Escreva("Digite o segundo número inteiro: ")
   Leia(num2)

   Escreva("Digite o terceiro número inteiro: ")
   Leia(num3)

   resultado <- num1 * num2 * num3

   Escreva("O resultado da multiplicação é: ")
   Escreval(resultado)

Fimalgoritmo
