Algoritmo "Média de 5 numeros"

Var

num1, num2, num3, num4, num5, media: real

Inicio
Escreva ("Digite o primeiro numero: ")
Leia (num1)

Escreva ("Digite o segundo numero: ")
Leia (num2)

Escreva ("Digite o terceiro numero: ")
Leia (num3)

Escreva ("Digite o quarto numero: ")
Leia (num4)

Escreva ("Digite o quinto numero: ")
Leia (num5)

media <- (num1 + num2 + num3 + num4 + num5)/5

Escreva ("A média dos 5 numeros é: ", media)

Fimalgoritmo